# -*- coding: utf-8 -*-
"""C24_2026_1_L1_Atividade_03_1926.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Dn4cNQQLpKnim2V18NLe5vblU3iOW-x

# **`Inatel - C24 (Inteligência Artificial) - 2026/1`**

# <font color='green'>**Atividade 03: Análise Exploratória de Dados (EDA)**</font>

## <font color='cyan'>**LEIA ATENTAMENTE AS INSTRUÇÕES A SEGUIR**</font>
- Importe este notebook no [Google Colab](https://colab.research.google.com/) para resolver os exercícios;
- Consulte o material disponibilizado pelo Prof. Felipe Figueiredo para revisar os conceitos;
- Utilize os recursos disponíveis na Internet (documentações e artigos científicos) para complementar seus estudos;
- <font color='red'>**A ATIVIDADE DEVERÁ SER REALIZADA _PRESENCIALMENTE_ COM O [MONITOR](mailto:matheus.botelho@ges.inatel.br), EM UM DOS SEGUINTES HORÁRIOS:**</font>

| Monitor                       | Dia           | Hora                              | Local           |
|-------------------------------|---------------|-----------------------------------|---------------- |
| Matheus Botelho Sampaio Netto | Segunda-feira | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Terça-feira   | <font color='orange'>17:30</font> | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quarta-feira  | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quinta-feira  | <font color='orange'>17:30</font> | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Sexta-feira   | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |

- <font color='red'>**NÃO**</font> remova as células de Código já presentes neste notebook;
- <font color='red'>**NÃO**</font> modifique as células de Markdown (em <font color='green'>verde</font> ou <font color='cyan'>ciano</font>) presentes neste notebook;
- Após cada questão, há uma célula para você implementar e responder a questão;
- É permitido adicionar mais células (de código ou markdown) antes da próxima pergunta;
- Caso precise utilizar bibliotecas que não estão instaladas nativamente no Colab, inclua uma célula de código com o comando de instalação.</font>
  - Exemplo: `!pip install nome_da_biblioteca`
- <font color='red'>**Renomeie os termos `LL` para `sua_turma_de_laboratório` e `MMMM` para `seu_numero_de_matricula` no nome do arquivo.**</font>
  - Exemplo: `C24_2026_1_L1_Atividade_02_1234.ipynb`)
- <font color='magenta'>**Faça download do notebook com a resolução no Google Colab, mantendo a saída de todas as células, e anexe-o à tarefa do Teams.**</font>

## <font color='green'>Contextualização</font>

### <font color='cyan'>Acesse o link indicado e, em um único parágrafo, descreva brevemente o dataset, incluindo: data de criação, domínio de aplicação, objetivo da base de dados e o tipo de informações que ela contém.
- #### <font color='cyan'>S., B. & Nagapadma, R. (2023). RT-IoT2022. UCI Machine Learning Repository. https://doi.org/10.24432/C5P338.</font>

data de criação: 01/04/2024; Domínio de Aplicação: Engenharia; Objetivo da base de dados: Dados de tráfego e dispositivos; Informações: 83 atributos tabulares.

## <font color='green'>Preparação</font>
"""

!pip install pandas ucimlrepo

import pandas as pd

from pprint import pprint
from ucimlrepo import fetch_ucirepo

ds = fetch_ucirepo(id=942)

pprint(ds.metadata)

ds.variables

X = ds.data.features
y = ds.data.targets

df = pd.concat([X, y], axis='columns')

df

"""## <font color='green'>**2.1 Conjuntos de Dados**</font>

### <font color='cyan'>Q1: Exiba 10 amostras aleatórias do conjunto de dados.</font>
"""

df.sample(10)

"""### <font color='cyan'>Q2: Quantas amostras o conjunto de dados possui?</font>"""

X.shape[1]

"""### <font color='cyan'>Q3: Quantas características o conjunto de dados possui?</font>"""

X.shape[0]

"""### <font color='cyan'>Q4: O conjunto de dados possui características numéricas? Se sim, escreva seu(s) nome(s) e classifique-a(s) como contínua(s) e/ou discreta(s).</font>
- #### <font color='cyan'>Observação: considere que uma caraterística numérica é discreta se possui menos que 50 valores únicos.</font>
"""

cat = df.select_dtypes(include=['object'])
cat.columns

"""### <font color='cyan'>Q5: O conjunto de dados possui características categóricas? Se sim, escreva seu(s) nome(s) e sua(s) quantidade(s) de valores únicos.</font>"""

arr2= []

for col in cat.columns:
    valores = df[col].nunique()
    arr2.append([col, valores])

pd.DataFrame(arr2, columns=["caracterstica","valores unicos"])

"""## <font color='green'>**2.2 Estatística Descritiva Básica**</font>

### <font color='cyan'> Q6: Escolha uma característica numérica do conjunto de dados. Escreva seu nome a seguir.</font>

fwd_pkts_per_sec

### <font color='cyan'> Q7: Calcule e mostre suas Medidas de Tendência Central (média, mediana e moda).</font>
"""

print(df['fwd_pkts_per_sec'].mean())
print(df['fwd_pkts_per_sec'].median())
print(df['fwd_pkts_per_sec'].mode()[0])

"""### <font color='cyan'> Q8: Calcule e mostre suas Medidas de Dispersão (mínimo, máximo e amplitude).</font>"""

print(df['fwd_pkts_per_sec'].min())
print(df['fwd_pkts_per_sec'].max())
print(df['fwd_pkts_per_sec'].max() - df['fwd_pkts_per_sec'].min())

"""## <font color='green'>**2.3 Análise Univariada**</font>

### <font color='cyan'> Q9: Escolha uma característica categórica do conjunto de dados. Escreva seu nome a seguir.</font>

proto

### <font color='cyan'> Q10: Crie e exiba uma Tabela de Frequência e/ou um Gráfico de Barras para a característica escolhida.</font>
"""

df["proto"].value_counts().plot(kind="bar")

"""### <font color='cyan'> Q11: Escolha uma característica numérica do conjunto de dados. Escreva seu nome a seguir.</font>

bwd_header_size_min

### <font color='cyan'> Q13: Crie e exiba um Histograma e/ou uma Estimativa de Densidade por Kernel (KDE) para a característica escolhida.</font>
"""

df["bwd_header_size_min"].hist()

"""## <font color='green'>**2.4 Análise Bivariada**</font>

### <font color='cyan'> Q14: Escolha duas características do conjuntos de dados. Escreva seus nome a seguir.</font>

proto e bwd_header_size_min

### <font color='cyan'>Q15: De acordo com os tipos das características escolhidas, produza pelo menos uma visualização de análise bivariada. Exemplos:</font>
- ### <font color='cyan'>Numérica vs Numérica: Scatter Plot ou Hexbin Plot;</font>
- ### <font color='cyan'>Categórica vs Numérica: Box Plot ou Violin Plot;</font>
- ### <font color='cyan'>Categórica vs Categórica: Crosstab, Grouped Bar Chart ou Stacked Bar Chart.</font>
"""

df.boxplot(column='bwd_header_size_min', by='proto')

"""## <font color='green'>**2.5 Identificação de Problemas nos Dados**</font>

### <font color='cyan'> Q16: Inspecione o conjuntos de dados para verificar se há:</font>
- #### <font color='cyan'> Dados Ausentes;</font>
- #### <font color='cyan'> Valores Atípicos (Outliers);</font>
- #### <font color='cyan'> Valores Duplicados;</font>
### <font color='cyan'> Reporte sua(s) descoberta(s) a seguir.</font>
"""

print(df.isnull().sum().sum())
print(df.duplicated().sum())
df.boxplot(column='bwd_header_size_min')

"""### <font color='cyan'> Q17: Caso problemas tenham sido encontrados, proponha soluções para eles.</font>
### <font color='cyan'> Exiba o conjunto de dados antes e depois de aplicar as soluções, enfatizando as mudanças.</font>
"""

#Não tem nenhum dado nulo, mas tem 5195 dados duplicados

df = df.drop_duplicates()
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    df = df[(df[col] >= lower) & (df[col] <= upper)]

print(df.isnull().sum().sum())
print(df.duplicated().sum())
df.boxplot(column='bwd_header_size_min')

"""## <font color='green'>**2.6 Correlação Simples**</font>

### <font color='cyan'> Q18: Escolha duas características numéricas do conjuntos de dados. Escreva seus nomes a seguir.</font>

flow_duration e fwd_pkts_per_sec

### <font color='cyan'> Q19: Calcule e exiba o Coeficiente de Correlação de Pearson ($r$) entre elas.</font>
"""

df[['flow_duration','fwd_pkts_per_sec']].corr(method='pearson')

"""### <font color='cyan'> Q20: Interprete o coeficiente de correlação, em termos de sinal e magnitude.</font>

O coeficiente de Pearson é igual a -0.86, o que mostra uma relação inversamente proporcional entre as duas, o que é mostrado pelo sinal negativo do resultado.
"""