# -*- coding: utf-8 -*-
"""C24_2026_1_LL_Atividade_06_1926.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCS3x8PI4ZyBpIZd0c0eER9ABqArB6Gm

# **`Inatel - C24 (Inteligência Artificial) - 2026/1`**

# <font color='green'>**Atividade 06: Classificação**</font>

## <font color='#2D9CDB'>**LEIA ATENTAMENTE AS INSTRUÇÕES A SEGUIR**</font>
- Importe este notebook no [Google Colab](https://colab.research.google.com/) para resolver os exercícios;
- Consulte o material disponibilizado pelo Prof. Felipe Figueiredo para revisar os conceitos;
- Utilize os recursos disponíveis na Internet (documentações e artigos científicos) para complementar seus estudos;
- <font color='red'>**A ATIVIDADE DEVERÁ SER REALIZADA COM O [MONITOR](mailto:matheus.botelho@ges.inatel.br) EM UM DOS SEGUINTES HORÁRIOS:**</font>

| Monitor                       | Dia           | Hora                               | Local           |
|-------------------------------|---------------|------------------------------------|---------------- |
| Matheus Botelho Sampaio Netto | Terça-feira   | <font color='orange'>17:30</font>  | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quinta-feira  | <font color='orange'>17:30</font>  | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Sábado        | <font color='#2D9CDB'>10:00</font> | Teams (ao vivo) |
| Matheus Botelho Sampaio Netto | Sábado        | <font color='#2D9CDB'>13:30</font> | Teams (ao vivo) |

- <font color='red'>**NÃO**</font> remova as células de Código já presentes neste notebook;
- <font color='red'>**NÃO**</font> modifique as células de Markdown (em <font color='green'>verde</font> ou <font color='#2D9CDB'>azul</font>) presentes neste notebook;
- Após cada questão, há uma célula para você implementar e responder a questão;
- É permitido adicionar mais células (de código ou markdown) antes da próxima pergunta;
- Caso precise utilizar bibliotecas que não estão instaladas nativamente no Colab, inclua uma célula de código com o comando de instalação.</font>
  - Exemplo: `!pip install nome_da_biblioteca`
- <font color='red'>**Renomeie os termos `LL` para `sua_turma_de_laboratorio` e `MMMM` para `seu_numero_de_matricula` no nome do arquivo.**</font>
  - Exemplo: `C24_2026_1_L1_Atividade_06_1234.ipynb`)
- <font color='magenta'>**Faça download do notebook com a resolução no Google Colab, mantendo a saída de todas as células, e anexe-o à tarefa do Teams.**</font>

# <font color='green'><u><b>Preparação</b></u></font>
"""

!pip install numpy pandas matplotlib seaborn scikit-learn ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

"""# <font color='green'><u><b>Parte 1 - Classificação Binária</b></u></font>

### <font color='#2D9CDB'>Acesse o link indicado e, em um único parágrafo, descreva brevemente o dataset, incluindo: domínio de aplicação, objetivo da base de dados e o tipo de informações que ela contém.</font>
- #### <font color='#2D9CDB'>Iranian Churn Dataset (2020). UCI Machine Learning Repository.</font>
  - #### <font color='#2D9CDB'>https://doi.org/10.24432/C5JW3Z</font>
  - #### <font color='#2D9CDB'>https://archive-beta.ics.uci.edu/dataset/563/iranian+churn+dataset</font>
"""

# fetch dataset
ds = fetch_ucirepo(id=563)

# metadata
display(ds.metadata)

# variable information
display(ds.variables)

# data (as pandas dataframe)
df = pd.concat([ds.data.features, ds.data.targets], axis='columns')

"""### <font color='#2D9CDB'>Q1) Exiba as primeiras linhas do dataframe, verifique suas dimensões e identifique a variável alvo (`TARGET_COLUMN`), respondendo com base nos resultados obtidos: quantas amostras e atributos o dataset possui, qual é o nome da variável alvo e se o problema é de classificação binária (justifique observando os valores únicos da variável alvo).</font>"""

TARGET_COLUMN = "Churn"

TARGET_COLUMN = "Churn"

display(df.head())

print(df.shape)

coluna = df.shape[1]
amostra = df.shape[0]

atributo = coluna - 1

print(amostra)
print(atributo)
print(coluna)
print(TARGET_COLUMN)
print(df[TARGET_COLUMN].unique())
print(df[TARGET_COLUMN].nunique())



"""O dataset possui 3150 amostras e 14 atributos. Variavel alvo = Churn. Trata-se de um problema de classificação binária, pois essa variável assume apenas dois valores (0 e 1).

### <font color='#2D9CDB'>Q2) Plote a distribuição da variável alvo utilizando o gráfico fornecido e, com base no resultado obtido, analise a proporção entre as classes para determinar se o dataset é balanceado ou desbalanceado, justificando sua resposta a partir da contagem de amostras em cada classe.</font>
"""

cont_classes = df[TARGET_COLUMN].value_counts().sort_index()
proporc_classes = df[TARGET_COLUMN].value_counts(normalize=True).sort_index() * 100

display(pd.DataFrame({
    "Contagem de classes": cont_classes,
    "Proporção de classes(%)": proporc_classes.round(2)
}))

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x=TARGET_COLUMN)
plt.title("Variavel alvo")
plt.xlabel(TARGET_COLUMN)
plt.ylabel("Quantidade")
plt.show()



"""O gráfico mostra que é desproporcional a quantidade de amostras na classe 0, pois ela tem mais quantidade do que a classe 1.

### <font color='#2D9CDB'>Q3) Gere a matriz de correlação entre os atributos do dataset e a variável alvo utilizando o gráfico fornecido e, com base nos valores apresentados, identifique quais atributos possuem maior correlação (positiva ou negativa) com a variável alvo, indicando quais podem ser mais relevantes para o problema de classificação.</font>
"""

corr = df.corr(numeric_only=True)

plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Matriz de Correlação")
plt.show()

corr_churn = corr[TARGET_COLUMN].drop(TARGET_COLUMN)

print("Correlação de atributos com a variável alvo:")
display(corr_churn.sort_values(key=abs, ascending=False).to_frame("Correlação com Churn"))

display(corr_churn.sort_values(ascending=False).head(5).to_frame("Correlação positiva"))

display(corr_churn.sort_values(ascending=True).head(5).to_frame("Correlação negativa"))



"""Os atributos mais correlacionados positivamente é o "Complains" e "Status", sendo mais indicados para ser relevados.

### <font color='#2D9CDB'>Q4) Aplique a técnica de Análise de Componentes Principais (PCA) para projetar os dados em duas dimensões e gere um gráfico de dispersão (scatter plot) utilizando as duas primeiras componentes principais, colorindo os pontos de acordo com a variável alvo; antes de aplicar o PCA, padronize os dados utilizando `StandardScaler`; em seguida, com base na visualização obtida, analise se há separação entre as classes e justifique sua resposta considerando a presença ou não de sobreposição entre os grupos.</font>
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_num = df.select_dtypes(include=['number'])

df_scaled = pd.DataFrame(
    scaler.fit_transform(df_num),
    columns=df_num.columns,
    index=df.index
)

corr_01 = df_scaled.corr()

plt.figure(figsize=(12, 8))
sns.heatmap(corr_01, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Matriz")
plt.show()

co = corr_01[TARGET_COLUMN].drop(TARGET_COLUMN)

display(co.sort_values(key=abs, ascending=False).to_frame("Correlação com Churn"))

display(co.sort_values(ascending=False).head(5).to_frame("Correlação positiva"))

display(co.sort_values(ascending=True).head(5).to_frame("Correlação negativa"))

"""Os atributos mais correlacionados positivamente é o "Complains" e "Status", indicando cancelamento. Já o "Seconds of Use", "Frequency of Use", "Customer Value" e "Distinct Called Numbers" possuem correlação negativa, mas ainda podem ser relevantes para a classificação.

### <font color='#2D9CDB'>Q5) Separe o dataset em variáveis de entrada (`X`) e variável alvo (`y`), divida os dados em conjuntos de treino e teste utilizando `train_test_split` (com 20% para teste) e `random_state=42`, e aplique a padronização dos atributos com `StandardScaler`; em seguida, explique por que a padronização é importante nesse contexto e por que o `fit` deve ser aplicado apenas no conjunto de treino.
"""

from sklearn.model_selection import train_test_split

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

scaler = StandardScaler()
scaledx = scaler.fit_transform(X_train)
testx = scaler.transform(X_test)

print(scaledx.shape)
print(testx.shape)
print(y_train.shape)
print(y_test.shape)

"""StandardScaler é necessário para colocar todos os atributos na mesma escala, para que o fit reconheça o desvio padrão e média

### <font color='#2D9CDB'>Q6) Treine um modelo de regressão logística utilizando os dados de treino (`X_train`, `y_train`) e, após o treinamento, verifique se o modelo convergiu corretamente; em seguida, descreva qual é o papel desse modelo no contexto do problema e o que ele está aprendendo a partir dos dados.</font>
"""

from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression(max_iter=1000, random_state=42)
modelo.fit(scaledx, y_train)

print(modelo.n_iter_[0])
print(modelo.max_iter)

if modelo.n_iter_[0] < modelo.max_iter:
    print("Conversão concluida")
else:
    print("Erro")

"""Regressão logística classifica se um cliente pertence à classe 0 ou 1 da variável Churn, se ele tende ou não convergir. O modelo está aprendendo a partir dos atributos dos clientes.

### <font color='#2D9CDB'>Q7) Utilize o modelo treinado para calcular as probabilidades previstas para o conjunto de teste (`predict_proba`) e exiba algumas delas; em seguida, interprete os valores obtidos explicando o que cada coluna representa e analise se o modelo está fazendo previsões com alta ou baixa confiança, com base na proximidade dos valores de 0 e 1.</font>
"""

p = modelo.predict_proba(testx)

print(modelo.classes_)
print(p[:10])

"""A maior parte das previsões apresentam alta confiança na classe 0, mas em situações como 0.5901, 0.4098, o modelo apresenta menor confiança.

### <font color='#2D9CDB'>Q8) Utilize as probabilidades previstas para gerar classificações com dois limiares diferentes (0.5 e 0.7) e compare os resultados obtidos; em seguida, analise como a alteração do limiar afeta as previsões do modelo, especialmente em relação à quantidade de falsos positivos e falsos negativos.</font>
"""

from sklearn.metrics import confusion_matrix

p_churn = p[:, 1]
pred05 = (p_churn >= 0.5).astype(int)
pred07 = (p_churn >= 0.7).astype(int)
tn05, fp05, fn05, tp05 = confusion_matrix(y_test, pred05).ravel()
tn07, fp07, fn07, tp07 = confusion_matrix(y_test, pred07).ravel()

resp = pd.DataFrame({
    "Limiar": [0.5, 0.7],
    "Previstos como 0": [(pred05 == 0).sum(), (pred07 == 0).sum()],
    "Previstos como 1": [(pred05 == 1).sum(), (pred07 == 1).sum()],
    "Falsos Positivos": [fp05, fp07],
    "Falsos Negativos": [fn05, fn07]
})
display(resp)

"""O modelo passa a exigir uma probabilidade maior para classificar um cliente como Churn igual a 1

### <font color='#2D9CDB'>Q9) Calcule as métricas de desempenho (acurácia, precisão, recall e F1-score) e a matriz de confusão para os dois limiares de decisão (0.5 e 0.7) utilizando a função fornecida e, com base nos resultados obtidos, compare o desempenho do modelo, identificando qual métrica foi mais impactada pela mudança do limiar e discutindo o trade-off observado entre precisão e recall.</font>
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

proba_churn = p[:, 1]

def avaliar_limiar(limiar):
    pred = (proba_churn >= limiar).astype(int)
    return {
        "Limiar": limiar,
        "Acurácia": accuracy_score(y_test, pred),
        "Precisão": precision_score(y_test, pred, zero_division=0),
        "Recall": recall_score(y_test, pred, zero_division=0),
        "F1-score": f1_score(y_test, pred, zero_division=0),
        "Matriz de Confusão": confusion_matrix(y_test, pred)
    }
resultado_05 = avaliar_limiar(0.5)

resultado_07 = avaliar_limiar(0.7)

metricas = pd.DataFrame([
    {
        "Limiar": resultado_05["Limiar"],
        "Acurácia": resultado_05["Acurácia"],
        "Precisão": resultado_05["Precisão"],
        "Recall": resultado_05["Recall"],
        "F1-score": resultado_05["F1-score"]
    },
    {
        "Limiar": resultado_07["Limiar"],
        "Acurácia": resultado_07["Acurácia"],
        "Precisão": resultado_07["Precisão"],
        "Recall": resultado_07["Recall"],
        "F1-score": resultado_07["F1-score"]
    }
])
display(metricas)

display(pd.DataFrame(resultado_05["Matriz de Confusão"],
                     index=["Real 0", "Real 1"],
                     columns=["Previsto 0", "Previsto 1"]))

display(pd.DataFrame(resultado_07["Matriz de Confusão"],
                     index=["Real 0", "Real 1"],
                     columns=["Previsto 0", "Previsto 1"]))

"""Aumentando o limiar de 0.5 para 0.7, o modelo fica mais complexo para prever Churn = 1. O que faz tender a reduzir falsos positivos e aumentar a precisão, contudo pode aumentar falsos negativos e reduzir o recall.

# <font color='green'><u><b>Parte 2 - Classificação Multiclasse</b></u></font>

### <font color='#2D9CDB'>Acesse o link indicado e, em um único parágrafo, descreva brevemente o dataset, incluindo: domínio de aplicação, objetivo da base de dados e o tipo de informações que ela contém.</font>
- #### <font color='#2D9CDB'>Blackard, J. (1998). Covertype Dataset. UCI Machine Learning Repository.</font>
  - #### <font color='#2D9CDB'>https://doi.org/10.24432/C50K5N</font>
  - #### <font color='#2D9CDB'>https://archive-beta.ics.uci.edu/dataset/31/covertype</font>
"""

# fetch dataset
ds = fetch_ucirepo(id=31)

# metadata
display(ds.metadata)

# variable information
display(ds.variables)

# data (as pandas dataframe)
df = pd.concat([ds.data.features, ds.data.targets], axis='columns').sample(frac=0.10, random_state=42)

"""### <font color='#2D9CDB'>Q10) Exiba as primeiras linhas do dataframe, verifique suas dimensões e identifique a variável alvo (`TARGET_COLUMN`), respondendo com base nos resultados obtidos: quantas amostras e atributos o dataset possui, qual é o nome da variável alvo e se o problema é de classificação binária (justifique observando os valores únicos da variável alvo).</font>"""

TARGET_COLUMN = ds.variables[ds.variables["role"] == "Target"]["name"].iloc[0]

display(df.head())

print(df.shape)
print(TARGET_COLUMN)
print(df[TARGET_COLUMN].unique())
print(df[TARGET_COLUMN].nunique())

amostras = df.shape[0]
atributos = df.shape[1] - 1

print(amostras)
print(atributos)



TARGET_COLUMN = None # preencher

"""Possui 58101 amostras e 55 colunas no total. Variável alvo = Cover_Type. O dataset tem mais de dois valores, portanto o problema não é de classificação binária.

### <font color='#2D9CDB'>Q11) Plote a distribuição da variável alvo utilizando o gráfico fornecido e, com base no resultado obtido, analise a proporção entre as classes para determinar se o dataset é balanceado ou desbalanceado, justificando sua resposta a partir da contagem de amostras em cada classe.</font>
"""

cont_02 = df[TARGET_COLUMN].value_counts().sort_index()
prop = df[TARGET_COLUMN].value_counts(normalize=True).sort_index() * 100

display(pd.DataFrame({
    "Contagem": cont_02,
    "Proporção (%)": prop.round(2)
}))

plt.figure(figsize=(8, 4))
sns.countplot(data=df, x=TARGET_COLUMN, order=cont_02.index)
plt.title("Distribuição da variável alvo")
plt.xlabel(TARGET_COLUMN)
plt.ylabel("Quantidade")
plt.show()



"""O dataset é desbalanceado, pois algumas classes possuem muito mais amostras do que outras. Portanto o modelo pode ter mais facilidade para aprender as classes majoritárias e mais dificuldade pro resto.

### <font color='#2D9CDB'>Q12) Gere a correlação entre os atributos e a variável alvo, ordene os valores e plote um gráfico de barras horizontais; destaque, no gráfico, os atributos com maior correlação em valor absoluto utilizando linhas de referência em |r| = 0.2 (valor adotado como um limiar heurístico para indicar correlações moderadas); em seguida, com base nos resultados, identifique quais variáveis podem ser mais relevantes para o modelo. Opcionalmente, pode-se imprimir os valores de correlação para facilitar a verificação numérica dos resultados e complementar a análise visual do gráfico.</font>
"""

correlacao = df.corr(numeric_only=True)[TARGET_COLUMN].drop(TARGET_COLUMN)

correlacao_ordenada = correlacao.reindex(
    correlacao.abs().sort_values(ascending=True).index
)
plt.figure(figsize=(10, 14))
correlacao_ordenada.plot(kind="barh")

plt.axvline(0.2, linestyle="--")
plt.axvline(-0.2, linestyle="--")
plt.title("Correlação de atributos + variavel alvo")
plt.xlabel("Correlação")
plt.ylabel("Atributos")
plt.show()

display(
    correlacao.reindex(
        correlacao.abs().sort_values(ascending=False).index
    ).to_frame("Correlação")
)



"""Variaveis relevantes para o modelo, são as de maior valor de correlação em valor absoluto e variável alvo, principalmente as que ultrapassam o limiar r = 0.2.

### <font color='#2D9CDB'>Q13) Aplique a técnica de Análise de Componentes Principais (PCA) para projetar os dados em duas dimensões e gere um gráfico de dispersão (scatter plot) utilizando as duas primeiras componentes principais, colorindo os pontos de acordo com a variável alvo; em seguida, com base na visualização obtida, analise se há separação entre as classes e justifique sua resposta considerando a presença ou não de sobreposição entre os grupos.</font>
"""

from sklearn.decomposition import PCA

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
df_pca = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
df_pca[TARGET_COLUMN] = y.values

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_pca, x="PC1", y="PC2", hue=TARGET_COLUMN, alpha=0.6, s=20)

plt.title("PCA")
plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.legend(title=TARGET_COLUMN)
plt.grid(True)
plt.show()

"""As classes não ficam totalmente separadas, com bastante sobreposição entre os grupos, e isso mostra que os dois primeiros componentes não são suficientes para separar as classes.

### <font color='#2D9CDB'>Q14) Separe o dataset em variáveis de entrada (`X`) e variável alvo (`y`), divida os dados em conjuntos de treino e teste utilizando `train_test_split` (com 20% para teste) e `random_state=42`, aplique a padronização dos atributos com `StandardScaler` e instancie um objeto de validação cruzada `KFold` com 5 divisões; em seguida, explique por que a validação cruzada (k-fold cross-validation) é importante para avaliar o desempenho de modelos de classificação.</font>
"""

from sklearn.model_selection import train_test_split, KFold

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

kf = KFold(n_splits=5, shuffle=True, random_state=42)

print(X_train_scaled.shape)
print(X_test_scaled.shape)
print(y_train.shape)
print(y_test.shape)
print(kf)

"""Porque ele separa os dados em várias partes, fazendo com que sejam analisadas, treinadas e testadas de forma diferente.

### <font color='#2D9CDB'>Q15) Utilize o objeto `KFold` instanciado anteriormente para treinar e avaliar um modelo de regressão logística multiclasse ao longo dos 5 folds no conjunto de treino, aplicando a padronização dentro de cada fold; durante o treinamento, exiba o número de iterações (`n_iter_`) em cada fold e verifique se o modelo convergiu corretamente; em seguida, reporte a média das métricas obtidas e descreva o papel do modelo no contexto do problema e o que ele está aprendendo a partir dos dados.</font>
"""

from sklearn.linear_model import LogisticRegression

res = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X_train), start=1):
    X_fold_train = X_train.iloc[train_idx]
    X_fold_val = X_train.iloc[val_idx]
    y_fold_train = y_train.iloc[train_idx]
    y_fold_val = y_train.iloc[val_idx]
    scaler = StandardScaler()
    X_fold_train_scaled = scaler.fit_transform(X_fold_train)
    X_fold_val_scaled = scaler.transform(X_fold_val)

    modelo = LogisticRegression(max_iter=1000, random_state=42)
    modelo.fit(X_fold_train_scaled, y_fold_train)
    pred = modelo.predict(X_fold_val_scaled)
    n_iter = modelo.n_iter_.max()
    convergiu = n_iter < modelo.max_iter
    print(fold, modelo.n_iter_, convergiu)

    res.append({
        "Acurácia": accuracy_score(y_fold_val, pred),
        "Precisão": precision_score(y_fold_val, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_fold_val, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_fold_val, pred, average="weighted", zero_division=0)
    })

media = pd.DataFrame(res)
display(media)
display(media.mean().to_frame("Média"))

"""Regressão logística multiclasse faz a previsão com base nos atributos padrões das classes, e assim descobrir que cobertura vai utilizar. A validação de 5 Kfolds faz com que o modelo analise diferentes divisões dos dados.

### <font color='#2D9CDB'>Q16) Treine um modelo final de regressão logística utilizando todo o conjunto de treino (`X_train`, `y_train`), aplicando regularização L2 (padrão do `scikit-learn`) com `C=0.01`; em seguida, aplique a padronização adequada e utilize o modelo para calcular as probabilidades previstas no conjunto de teste (`predict_proba`); exiba algumas dessas probabilidades e interprete os valores obtidos, explicando o que cada coluna representa e analisando se o modelo está fazendo previsões com alta ou baixa confiança.</font>
"""

scaler = StandardScaler()

X_train_final = scaler.fit_transform(X_train)
X_test_final = scaler.transform(X_test)

modelo = LogisticRegression(C=0.01, max_iter=1000, random_state=42)
modelo.fit(X_train_final, y_train)

prob = modelo.predict_proba(X_test_final)
print(modelo.classes_)

display(pd.DataFrame(
    prob[:10],
    columns=[f"Classe {classe}" for classe in modelo.classes_]
))

"""A probabilidade da amostra pertencer a uma classe da variável alvo é representado pela coluna. Quando uma linha possui a probabilidade maior que as outras (mais próximo de 1), o modelo se mostra muito mais confiante, e quando os valores ficam próximos entre várias classes, ele se mostra menos confiante para fazer a previsão.

### <font color='#2D9CDB'>Q17) Treine um modelo de regressão logística sem regularização (`penalty=None`) utilizando o mesmo procedimento de padronização e conjunto de treino; em seguida, calcule as probabilidades previstas no conjunto de teste (`predict_proba`), exiba algumas delas (usando os mesmos índices de amostras da questão anterior) e analise os resultados novamente.</font>
"""

modelo_sem_reg = LogisticRegression(
    penalty=None,
    max_iter=1000,
    random_state=42
)

modelo_sem_reg.fit(X_train_final, y_train)
prob_sem_reg = modelo_sem_reg.predict_proba(X_test_final)
indices = range(10)
print(modelo_sem_reg.classes_)

display(pd.DataFrame(
    prob_sem_reg[indices],
    columns=[f"Classe {classe}" for classe in modelo_sem_reg.classes_]
))

"""O modelo se mostra bem mais limitado, eu corre o risco de causar overfitting por conta do aumento da confiança nas previsões nos dados de treino.

### <font color='#2D9CDB'>Q18) Compare as probabilidades previstas pelos modelos com e sem regularização e analise as diferenças observadas, considerando: (i) a concentração das probabilidades em uma única classe, (ii) o nível de confiança das previsões e (iii) possíveis indícios de overfitting; para apoiar sua análise, calcule a confiança média dos modelos (considerando, para cada amostra, a maior probabilidade prevista) e utilize esse valor na comparação.</font>
"""

config_reg = p.max(axis=1)
config_sem_reg = prob_sem_reg.max(axis=1)

comp = pd.DataFrame({
    "Modelo": ["Com regularização", "Sem regularização"],
    "Confiança média": [config_reg.mean(), config_sem_reg.mean()]
})
display(comp)
display(pd.DataFrame({
    "Regularizado": config_reg[:10],
    "Sem regularização": config_sem_reg[:10],
    "Diferença": config_sem_reg[:10] - config_reg[:10]
}))

"""O modelo com regularização é mais controlado nas previsões, enquanto o modelo sem regularização tende a apresentar probabilidades concentradas em uma única classe, resultando em uma média de confiança maior, mas essa confiança maior nem sempre significa melhor desempenho, pois pode indicar maior risco de overfitting.

### <font color='#2D9CDB'>Q19) Utilize o `classification_report` para avaliar o desempenho dos modelos com e sem regularização no conjunto de teste; em seguida, compare os resultados obtidos, analisando as métricas de precisão, recall e F1-score para cada classe e discutindo possíveis diferenças no desempenho entre os modelos.</font>
"""

from sklearn.metrics import classification_report

desempenho_reg = modelo.predict(X_test_final)
desempenho_sem_reg = modelo_sem_reg.predict(X_test_final)

print(classification_report(y_test, desempenho_reg, zero_division=0))
print(classification_report(y_test, desempenho_sem_reg, zero_division=0))

"""O melhor modelo é aquele que tem um valor de precision, recall e F1-score maiores, principalmente nas classes com menor quantidade de amostras. Se o modelo sem regularização tiver métricas maiores, ele se ajustou melhor ao teste, se a diferença for pequena o modelo regularizado pode ser preferível por ser mais controlado e menos propenso a overfitting.

### <font color='#2D9CDB'>Q20) Calcule a matriz de confusão normalizada (por linha, com duas casas de precisão) para os modelos com e sem regularização no conjunto de teste; em seguida, plote ambas as matrizes e compare os resultados, analisando quais classes são melhor classificadas, quais apresentam maior confusão e como a regularização impacta o desempenho entre as classes.</font>
"""

from sklearn.metrics import confusion_matrix

pred_reg = modelo.predict(X_test_final)
pred_sem_reg = modelo_sem_reg.predict(X_test_final)

matriz_reg = confusion_matrix(y_test, pred_reg, normalize="true")
matriz_sem_reg = confusion_matrix(y_test, pred_sem_reg, normalize="true")

matriz_reg = pd.DataFrame(matriz_reg, index=modelo.classes_, columns=modelo.classes_)
matriz_sem_reg = pd.DataFrame(matriz_sem_reg, index=modelo_sem_reg.classes_, columns=modelo_sem_reg.classes_)

plt.figure(figsize=(8, 6))
sns.heatmap(matriz_reg, annot=True, fmt=".2f", cmap="Blues")

plt.title("Matriz Normalizada com Regularização")
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(matriz_sem_reg, annot=True, fmt=".2f", cmap="Blues")

plt.title("Matriz Normalizada sem Regularização")
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.show()

"""As classes com maior classificação são as com maiores a diagonal dominante. Valores altos fora da diagonal principal indicam confusão entre classes. É possível verificar se a regularização reduziu ou aumentou os erros entre classes específicas se comparado as matrizes."""