# -*- coding: utf-8 -*-
"""C24_2026_1_L1_Atividade_04_1926.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOs24XHAshOT4VPI7LaoA7GVW2IB9d1B

# **`Inatel - C24 (Inteligência Artificial) - 2026/1`**

# <font color='green'>**Atividade 04: Transformações dos Dados (Pré-processamento)**</font>

## <font color='cyan'>**LEIA ATENTAMENTE AS INSTRUÇÕES A SEGUIR**</font>
- Importe este notebook no [Google Colab](https://colab.research.google.com/) para resolver os exercícios;
- Consulte o material disponibilizado pelo Prof. Felipe Figueiredo para revisar os conceitos;
- Utilize os recursos disponíveis na Internet (documentações e artigos científicos) para complementar seus estudos;
- <font color='red'>**A ATIVIDADE DEVERÁ SER REALIZADA _PRESENCIALMENTE_ COM O [MONITOR](mailto:matheus.botelho@ges.inatel.br), EM UM DOS SEGUINTES HORÁRIOS:**</font>

| Monitor                       | Dia           | Hora                              | Local           |
|-------------------------------|---------------|-----------------------------------|---------------- |
| Matheus Botelho Sampaio Netto | Segunda-feira | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Terça-feira   | <font color='orange'>17:30</font> | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quarta-feira  | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quinta-feira  | <font color='orange'>17:30</font> | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Sexta-feira   | <font color='cyan'>13:30</font>   | 1.4 (prédio VI) |

- <font color='red'>**NÃO**</font> remova as células de Código já presentes neste notebook;
- <font color='red'>**NÃO**</font> modifique as células de Markdown (em <font color='green'>verde</font> ou <font color='cyan'>ciano</font>) presentes neste notebook;
- Após cada questão, há uma célula para você implementar e responder a questão;
- É permitido adicionar mais células (de código ou markdown) antes da próxima pergunta;
- Caso precise utilizar bibliotecas que não estão instaladas nativamente no Colab, inclua uma célula de código com o comando de instalação.</font>
  - Exemplo: `!pip install nome_da_biblioteca`
- <font color='red'>**Renomeie os termos `LL` para `sua_turma_de_laboratorio` e `MMMM` para `seu_numero_de_matricula` no nome do arquivo.**</font>
  - Exemplo: `C24_2026_1_L1_Atividade_04_1234.ipynb`)
- <font color='magenta'>**Faça download do notebook com a resolução no Google Colab, mantendo a saída de todas as células, e anexe-o à tarefa do Teams.**</font>

## <font color='green'>Contextualização</font>

### <font color='cyan'>Acesse o link indicado e, em um único parágrafo, descreva brevemente o dataset, incluindo: domínio de aplicação, objetivo da base de dados e o tipo de informações que ela contém.</font>
- #### <font color='cyan'>Sakar, C. & Kastro, Y. (2018). Online Shoppers Purchasing Intention Dataset. UCI Machine Learning Repository. https://doi.org/10.24432/C5F88Q</font>

É um dataset que mostra dados sobre a intenção de compras online de usuários, que contem informações sobre o tipo de usuários que visitam as páginas, número de visualizações, a data que foram visitadas, com o objetivo de melhorar a estratégia de venda da loja online.

## <font color='green'>Preparação</font>
"""

!pip install pandas scikit-learn ucimlrepo

import pandas as pd
from ucimlrepo import fetch_ucirepo

ds = fetch_ucirepo(id=468)

_X_uci = ds.data.features
_y_uci = ds.data.targets

df = pd.concat([_X_uci, _y_uci], axis='columns')
df.head()

"""## <font color='green'>**3.1 Divisão do Dataset**</font>

### <font color='cyan'>Q1: Explique com suas palavras por que nunca devemos realizar transformações (como escalonamento) no dataset inteiro antes de dividi-lo em treino e teste.</font>

Porque o modelo acaba analisando os testes junto com o treino, e isso acaba gerando resultados muito melhores do que resultados reais.

### <font color='cyan'>Q2: Utilizando a função `train_test_split` biblioteca `scikit-learn`, divida as variáveis independentes (`X`) e a variável alvo (`y`) em conjuntos de treinamento (80%) e teste (20%).</font>
- #### <font color='cyan'> Lembre-se de fixar uma semente do gerador de números aleatórios (`random_state`) para reprodutibilidade dos resultados.</font>
"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(_X_uci, _y_uci, test_size = 0.2, random_state = 1)

"""## <font color='green'>**3.2 Codificação de Atributos Categóricos**</font>

### <font color='cyan'>Q3: Identifique pelo menos duas variáveis categóricas no seu conjunto de dados de treinamento (`X_train`).</font>
"""

x_trainobj = x_train.select_dtypes(include = "object").nunique()
print(x_trainobj)

"""### <font color='cyan'>Q4: Escolha uma das variáveis categóricas nominais identificadas na questão anterior. Selecione essa coluna no seu conjunto de treinamento (`X_train`) e exiba 10 amostras originais.</font>
- #### <font color='cyan'> Lembre-se de fixar uma semente do gerador de números aleatórios (`random_state`) para reprodutibilidade dos resultados.</font>
"""

x_tmonth = x_train.iloc[:, 10].sample(10, random_state = 2)
print(x_tmonth)

"""### <font color='cyan'>Q5: Aplique a técnica de `One-Hot Encoding` na variável escolhida utilizando a biblioteca scikit-learn.</font>
- #### <font color='cyan'>Lembre-se de utilizar o método `fit_transform` no conjunto de treinamento e apenas `transform` no conjunto de teste.</font>
- #### <font color='cyan'>Observação: Ao instanciar o `OneHotEncoder`, utilize os parâmetros `sparse_output=False` (para facilitar a visualização dos dados como um array tradicional) e `handle_unknown='ignore'` (para evitar erros caso o conjunto de teste contenha alguma categoria que não existia no conjunto de treinamento).</font>
"""

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)
x_enc = encoder.fit_transform(x_tmonth.to_frame())

"""### <font color='cyan'>Q6: Exiba as mesmas 10 amostras (agora transformadas) no conjunto de treinamento. Explique brevemente o que aconteceu com a estrutura dos dados originais após a aplicação da técnica.</font>
- #### <font color='cyan'>Dica: Como o resultado do transformador é um array NumPy, você pode utilizar o método `encoder.get_feature_names_out()` para descobrir os nomes das novas colunas geradas e facilitar a visualização em um novo DataFrame.</font>
"""

print(x_enc)

# Resposta: A tecnica OneHotEncoder transformou cada categoria em uma nova coluna e preencheu com 0 e 1

x_enc_name = encoder.get_feature_names_out(["Month"])

print("\n")

print(x_enc_name)

"""## <font color='green'>**3.3 Escalonamento de Atributos**</font>

### <font color='cyan'>Q7: Por que algoritmos baseados em distância (como `kNN`) precisam que os dados numéricos estejam escalonados na mesma proporção?</font>

Porque métodos como kNN utilizam a distância para calcularem, e escalar ajuda a calcular e evitar desvios.

### <font color='cyan'>Q8: Selecione uma coluna numérica contínua de `X_train`. Escreva o nome da característica selecionada abaixo.</font>
"""

x_n = x_train["ProductRelated_Duration"]
print(x_n)

#Resposta: Duração do produto

"""### <font color='cyan'>Q9: Calcule e exiba as estatísticas descritivas dessa variável original (Média, Mediana, Desvio Padrão, Mínimo e Máximo).</font>"""

print(x_n.mean(), "\n") #Média
print(x_n.median(), "\n") #Mediana
print(x_n.std(), "\n") #Desvio padrao
print(x_n.min(), "\n") #Minimo
print(x_n.max(), "\n") #Maximo

"""### <font color='cyan'>Q10: Plote um gráfico mostrando sua distribuição original por meio de um [Histograma](https://seaborn.pydata.org/generated/seaborn.histplot.html)).</font>
- #### <font color='cyan'>Recomendado: adicione também uma curva de [Estimativa de Densidade de Kernel](https://pt.wikipedia.org/wiki/Estimativa_de_densidade_kernel) ao histograma; veja como no link acima.</font>
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

sns.histplot(x_n, bins=30, kde=True, color='blue')

plt.title('Histograma ProductRelated_Duration')
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

"""### <font color='cyan'>Q11: Aplique o Escalonamento nesta variável. Você pode escolher entre a Padronização (`StandardScaler`) ou a Normalização (`MinMaxScaler`), ambas da biblioteca scikit-learn.</font>

- #### <font color='cyan'>Atenção: Realize a transformação e substitua os valores da coluna original no DataFrame (`X_train` e `X_test`) pelos valores escalonados.</font>
- #### <font color='cyan'>Lembre-se de utilizar o método `fit_transform` no conjunto de treinamento e apenas `transform` no conjunto de teste.</font>
"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train["ProductRelated_Duration"] = scaler.fit_transform(x_train[["ProductRelated_Duration"]])

x_test["ProductRelated_Duration"] = scaler.transform(x_test[["ProductRelated_Duration"]])

"""### <font color='cyan'>Q12: Calcule e exiba as estatísticas descritivas dessa variável transformada (Média, Mediana, Desvio Padrão, Mínimo e Máximo).</font>"""

x_train["ProductRelated_Duration"] = scaler.fit_transform(x_train[["ProductRelated_Duration"]])

x_test["ProductRelated_Duration"] = scaler.transform(x_test[["ProductRelated_Duration"]])

print(x_train["ProductRelated_Duration"].mean(), "\n") #Média
print(x_train["ProductRelated_Duration"].median(), "\n") #Mediana
print(x_train["ProductRelated_Duration"].std(), "\n") #Desvio padrao
print(x_train["ProductRelated_Duration"].min(), "\n") #Minimo
print(x_train["ProductRelated_Duration"].max(), "\n") #Maximo

print("\n")

print(x_test["ProductRelated_Duration"].mean(), "\n") #Média
print(x_test["ProductRelated_Duration"].median(), "\n") #Mediana
print(x_test["ProductRelated_Duration"].std(), "\n") #Desvio padrao
print(x_test["ProductRelated_Duration"].min(), "\n") #Minimo
print(x_test["ProductRelated_Duration"].max(), "\n") #Maximo

"""### <font color='cyan'>Q13: Plote um gráfico mostrando sua distribuição transformada por meio de um [Histograma](https://seaborn.pydata.org/generated/seaborn.histplot.html)).</font>
- #### <font color='cyan'>Recomendado: adicione também uma curva de [Estimativa de Densidade de Kernel](https://pt.wikipedia.org/wiki/Estimativa_de_densidade_kernel) ao histograma; veja como no link acima.</font>
"""

x_test["ProductRelated_Duration"] = scaler.transform(x_test[["ProductRelated_Duration"]])

sns.histplot(x_test["ProductRelated_Duration"], bins=30, kde=True, color='blue')

plt.title('Histograma x_test ProductRelated_Duration')
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

x_train["ProductRelated_Duration"] = scaler.transform(x_train[["ProductRelated_Duration"]])

sns.histplot(x_train["ProductRelated_Duration"], bins=30, kde=True, color='blue')

plt.title('Histograma x_test ProductRelated_Duration')
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

"""### <font color='cyan'>Q14: Compare os valores e os gráficos antes e depois do escalonamento.</font>
- #### <font color='cyan'>O que aconteceu com a média e o desvio padrão (ou com o mínimo e máximo)?</font>
- #### <font color='cyan'>O que aconteceu com a escala do eixo X e com o formato da curva no gráfico?</font>

A média e desvio padrão máximo de x_test diminuiu em comparação com x_train, enquanto o resto dos dados se mantiveram em valores próximos.

## <font color='green'>**3.4 Engenharia de Atributos (Feature Engineering)**</font>

### <font color='cyan'>Q15: A partir dos atributos originais, crie uma nova coluna (atributo) no dataset que possa ser informativa para um modelo preditivo. Explique a lógica da sua nova variável.</font>
- #### <font color='cyan'>Você pode combinar a taxa de rejeição e a taxa de saída (`BounceRates` e `ExitRates`) para criar uma variável de `Total_Abandon` (soma das taxas).</font>
"""

x_train["Total_Abandon"] = x_train["BounceRates"] + x_train["ExitRates"]
x_test["Total_Abandon"] = x_test["BounceRates"] + x_test["ExitRates"]

print(x_train["Total_Abandon"], "\n")
print(x_test["Total_Abandon"])

"""### <font color='cyan'>Q16: Selecione essa nova coluna no seu conjunto de treinamento (`X_train`) e exiba 10 amostras.</font>
- #### <font color='cyan'> Lembre-se de fixar uma semente do gerador de números aleatórios (`random_state`) para reprodutibilidade dos resultados.</font>
"""

x_total_abandon = x_train["Total_Abandon"].sample(10, random_state = 4)
print(x_total_abandon)

"""### <font color='cyan'>Q17: Calcule a correlação de Pearson dessa nova variável com a variável alvo (`y_train`).</font>
- #### <font color='cyan'>A correlação foi negativa, neutra ou positiva? Forte ou fraca?</font>
- #### <font color='cyan'>Isso indica que o seu novo atributo potencialmente ajudará um modelo de ML?</font>
- #### <font color='cyan'>Importante: Utilize o `LabelEncoder` da biblioteca `scikit-learn` para transformar a variável alvo (`y_train`) em valores numéricos (0 e 1) antes de calcular a correlação.</font>
"""

from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

y_label = label.fit_transform(y_train)

y_label_series = pd.Series(y_label, index=y_train.index)

corr_pearson = x_train["Total_Abandon"].corr(y_label_series)

print(corr_pearson)

#A correlação foi negativa, e de forma fraca, pois esta longe do valor -1

"""## <font color='green'>**3.5 Extração / Seleção de Atributos**</font>

### <font color='cyan'>Q18: Qual a principal diferença conceitual entre Extração de Atributos (ex: `Principal Component Analysis`) e Seleção de Atributos (ex: `Variance Threshold`)? Explique.</font>

A PCA cria novos atributos a partir da combinação dos atributos originais e são descartados, enquanto a Seleção de Atributos seleciona um subconjunto dos atributos originais e apenas descarta os menos reelevantes

### <font color='cyan'>Q19: Aplique a técnica de Análise de Componentes Principais (PCA) em todas as variáveis numéricas escalonadas.</font>

- #### <font color='cyan'>a) Inicialmente, instancie o modelo `PCA` da biblioteca `scikit-learn` sem limitar o número de componentes (ou seja, extraindo todos os componentes possíveis) e ajuste-o aos dados de treinamento.</font>
- #### <font color='cyan'>b) Crie um gráfico de dispersão (Scatter Plot) mostrando a variância explicada cumulativa em função do número de componentes.</font>
  - #### <font color='cyan'>Observação: adicione uma linha de corte horizontal em 99,9%.</font>
  - #### <font color='cyan'>Dica: você pode usar a função `np.cumsum()` sobre o atributo `explained_variance_ratio_` do objeto PCA.</font>
- #### <font color='cyan'>c) A partir da análise visual, qual a quantidade mínima de componentes para atingir o critério de 99,9%? Justifique por que escolher um limiar tão alto.</font>
"""

from sklearn.decomposition import PCA

x_num = x_train.select_dtypes(include="number")
pca = PCA()
pca.fit(x_num)

var = np.cumsum(pca.explained_variance_ratio_)

plt.figure()
plt.plot(var)

plt.axhline(y=0.999,)
plt.title('Variancia explicada cumulativa')
plt.xlabel('Componentes (N)')
plt.ylabel('Variancia')
plt.show()

print("\n")

n_comp = np.argmax(var >= 0.999) + 1
print("Quantidade minima de componentes =", n_comp)

#O motivo do linear ser 99,9% é para evitar perda de dados e se manter o mais próximo do dataset

"""### <font color='cyan'>Q20: Aplique a transformação PCA final utilizando o critério de 99,9% de variância explicada.</font>
- #### <font color='cyan'>a) Instancie um novo modelo PCA com essa quantidade de componentes e aplique a transformação nos conjuntos de treino e teste.</font>
- #### <font color='cyan'>b) Exiba o shape dos dados antes e depois da transformação para confirmar a redução de dimensionalidade.</font>
- #### <font color='cyan'>c) Quais são os 3 principais atributos que mais influenciam a primeira Componente Principal (PC1)?</font>
  - #### <font color='cyan'>Dica: Analise os `components_` do modelo PCA final e identifique os maiores valores absolutos.</font>
"""

from sklearn.decomposition import PCA

pca_final = PCA(n_comp)

x_num2 = x_test.select_dtypes(include="number")

xtrain_pca = pca_final.fit_transform(x_num)
xtest_pca = pca_final.transform(x_num2)

print("Treino:")
print(x_num.shape)
print(xtrain_pca.shape)
print("\n")

print("Teste:")
print(x_num2.shape)
print(xtest_pca.shape)

pc1 = pca_final.components_[0]

features = x_num.columns

indices = np.argsort(np.abs(pc1))[::-1]

top3 = [(features[i], pc1[i]) for i in indices[:3]]

print("3 principais atributos:")
for nome, valor in top3:
    print(f"{nome}: {valor}")