# -*- coding: utf-8 -*-
"""C24_2026_1_L1_Atividade_05_1926.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19h7GJ7W-2CTgK3QfSVhEdODm9ZqSLTgg

# **`Inatel - C24 (Inteligência Artificial) - 2026/1`**

# <font color='green'>**Atividade 05: Regressão**</font>

## <font color='#2D9CDB'>**LEIA ATENTAMENTE AS INSTRUÇÕES A SEGUIR**</font>
- Importe este notebook no [Google Colab](https://colab.research.google.com/) para resolver os exercícios;
- Consulte o material disponibilizado pelo Prof. Felipe Figueiredo para revisar os conceitos;
- Utilize os recursos disponíveis na Internet (documentações e artigos científicos) para complementar seus estudos;
- <font color='red'>**A ATIVIDADE DEVERÁ SER REALIZADA COM O [MONITOR](mailto:matheus.botelho@ges.inatel.br) EM UM DOS SEGUINTES HORÁRIOS:**</font>

| Monitor                       | Dia           | Hora                               | Local           |
|-------------------------------|---------------|------------------------------------|---------------- |
| Matheus Botelho Sampaio Netto | Terça-feira   | <font color='orange'>17:30</font>  | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Quinta-feira  | <font color='orange'>17:30</font>  | 1.4 (prédio VI) |
| Matheus Botelho Sampaio Netto | Sábado        | <font color='#2D9CDB'>10:00</font> | Teams (ao vivo) |
| Matheus Botelho Sampaio Netto | Sábado        | <font color='#2D9CDB'>13:30</font> | Teams (ao vivo) |

- <font color='red'>**NÃO**</font> remova as células de Código já presentes neste notebook;
- <font color='red'>**NÃO**</font> modifique as células de Markdown (em <font color='green'>verde</font> ou <font color='#2D9CDB'>azul</font>) presentes neste notebook;
- Após cada questão, há uma célula para você implementar e responder a questão;
- É permitido adicionar mais células (de código ou markdown) antes da próxima pergunta;
- Caso precise utilizar bibliotecas que não estão instaladas nativamente no Colab, inclua uma célula de código com o comando de instalação.</font>
  - Exemplo: `!pip install nome_da_biblioteca`
- <font color='red'>**Renomeie os termos `LL` para `sua_turma_de_laboratorio` e `MMMM` para `seu_numero_de_matricula` no nome do arquivo.**</font>
  - Exemplo: `C24_2026_1_L1_Atividade_05_1234.ipynb`)
- <font color='magenta'>**Faça download do notebook com a resolução no Google Colab, mantendo a saída de todas as células, e anexe-o à tarefa do Teams.**</font>

## <font color='green'>Contextualização</font>

### <font color='#2D9CDB'>Acesse o link indicado e, em um único parágrafo, descreva brevemente o dataset, incluindo: domínio de aplicação, objetivo da base de dados e o tipo de informações que ela contém.</font>
- #### <font color='#2D9CDB'>R. Quinlan. "Auto MPG," UCI Machine Learning Repository, 1993. https://doi.org/10.24432/C5859H.</font>

## <font color='green'>Preparação</font>
"""

!pip install pandas scikit-learn ucimlrepo

from ucimlrepo import fetch_ucirepo

# Importar o dataset Auto MPG (ID 9)
auto_mpg = fetch_ucirepo(id=9)

# Extrair as variáveis independentes (X) e a variável alvo (y)
X = auto_mpg.data.features
y = auto_mpg.data.targets

# Ver as primeiras linhas
display(X.head())

"""## <font color='green'>**1. Análise Exploratória de Dados (EDA)**</font>

### <font color='cyan'>Q1) Verifique se há amostras com valores ausentes no conjunto de dados. Se houver, remova-as e informe quantas foram removidas.</font>
"""

# A coluna "horsepower" tem 6 valores ausentes escritos: "?"
import pandas as pd

X = X.replace("?", pd.NA)
X = X.apply(pd.to_numeric, errors='coerce')

print("Quantidade de ? removidos =",X.isna().sum().sum())

"""### <font color='cyan'>Q2) Plote um histograma da coluna alvo `y` (MPG) utilizando `matplotlib` ou `seaborn`. Adicione título e rótulos aos eixos.</font>"""

import matplotlib.pyplot as plt

plt.figure()
plt.hist(y, bins=20)

plt.title("Distribuição do Consumo")
plt.xlabel("MPG (Milhas por Galão)")
plt.ylabel("Frequência")
plt.grid(True)
plt.show()

"""### <font color='cyan'>Q3) O que a distribuição do histograma nos diz sobre o consumo de combustível da maioria dos carros desse dataset?</font>

A maioria dos carros gastam entre 15 até 30 Milhas por Galão (MPG), e poucos carros gastam menos que 15 e mais que 30.

## <font color='green'>**2. Regressão Linear, Polinomial e Visualização**</font>

### <font color='cyan'>Q4) Crie um gráfico de dispersão (scatter plot) de `weight` vs `mpg`.</font>
"""

x_weight = X['weight']

plt.figure()
plt.scatter(x_weight, y)
plt.title("Dispersão de peso por MPG")
plt.xlabel("Peso")
plt.ylabel("MPG (Milhas por Galão)")
plt.grid(True)
plt.show()

"""### <font color='cyan'>Q5) Observando o gráfico de dispersão gerado na questão anterior, como você descreveria a relação entre o peso do veículo (weight) e o consumo de combustível (mpg)? A relação parece ser estritamente linear ou apresenta um comportamento não linear? Justifique sua resposta.</font>

É um comportamento linear de forma negativa, a relação que podemos observar é que, quanto maior o peso do carro, maior o seu consumo de combustível, mostrando que carros mais pesados gastam mais combustível para andar.

### <font color='cyan'>Q6) Divida o conjunto de dados em treinamento (80%) e teste (20%), utilizando a variável `weight` como entrada e `mpg` como alvo, e em seguida construa um gráfico de dispersão que apresente os dois subconjuntos com cores diferentes, incluindo título, rótulos dos eixos e uma legenda para identificar claramente os dados de treino e de teste.</font>
"""

from sklearn.model_selection import train_test_split

X_weight = X[["weight"]]
y_mpg = y.squeeze()

X_train, X_test, y_train, y_test = train_test_split(
    X_weight, y_mpg,
    test_size=0.2,
    random_state = 2
)

plt.figure()
plt.scatter(X_train["weight"], y_train, label="Treinamento")
plt.scatter(X_test["weight"], y_test, label="Teste")
plt.title("Dispersão de peso por MPG)")
plt.xlabel("Peso do carro")
plt.ylabel("Consumo (MPG)")
plt.legend()
plt.show()

"""### <font color='cyan'>Q7) Com base na distribuição dos pontos no gráfico gerado, os conjuntos de treinamento e teste parecem ser representativos do conjunto de dados original? Justifique sua resposta observando a dispersão das cores.</font>

Observando a dispersão das cores, os dados de teste parecem ser bons representativos do conjunto original, mantendo a relação direta do peso por consumo.

### <font color='green'>Antes de avaliarmos nosso modelo, vamos entender brevemente o que cada métrica significa e quais funções da biblioteca [`sklearn.metrics`](https://scikit-learn.org/stable/api/sklearn.metrics.html) utilizaremos:</font>
- #### <font color='green'>R² (Coeficiente de Determinação) - função `r2_score(y_true, y_pred)`: Mede o quão bem o modelo se ajusta aos dados. Ele indica a proporção da variabilidade da variável alvo (MPG) que é explicada pelo modelo. Varia geralmente de 0 a 1 (podendo ser negativo se o modelo for pior que uma linha média). Quanto mais próximo de 1, melhor.</font>
- #### <font color='green'>MAE (Erro Absoluto Médio - Mean Absolute Error) - função `mean_absolute_error(y_true, y_pred)`: Representa a média das diferenças em valor absoluto entre as previsões do modelo e os valores reais. É uma métrica muito intuitiva porque o erro é retornado na mesma unidade da variável alvo (ou seja, errar por "3 MPG"). Quanto menor, melhor.</font>
- #### <font color='green'>MSE (Erro Quadrático Médio - Mean Squared Error) - função `mean_squared_error(y_true, y_pred)`: Calcula a média dos erros elevados ao quadrado. Como os erros são elevados ao quadrado, o MSE penaliza erros maiores (outliers) de forma mais severa do que o MAE. Quanto menor, melhor.</font>

### <font color='cyan'>Q8) Importe as funções `r2_score`, `mean_absolute_error` e `mean_squared_error` do módulo `sklearn.metrics`. Em seguida, treine um modelo de Regressão Linear Simples para prever o MPG usando o peso. Faça as previsões para o conjunto de treinamento e para o conjunto de teste. Por fim, imprima as métricas (R², MAE e MSE) para ambos os conjuntos.</font>
"""

from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

modelo = LinearRegression()
modelo.fit(X_train, y_train)

y_train_previsao = modelo.predict(X_train)
y_test_previsao = modelo.predict(X_test)

# Treino
r2_train = r2_score(y_train, y_train_previsao)
mae_train = mean_absolute_error(y_train, y_train_previsao)
mse_train = mean_squared_error(y_train, y_train_previsao)

# Teste
r2_test = r2_score(y_test, y_test_previsao)
mae_test = mean_absolute_error(y_test, y_test_previsao)
mse_test = mean_squared_error(y_test, y_test_previsao)

print("Treino:\n")
print("R2:", r2_train)
print("MAE:", mae_train)
print("MSE:", mse_train)

print("\nTeste: \n")
print("R2:", r2_test)
print("MAE:", mae_test)
print("MSE:", mse_test)

"""### <font color='cyan'>Q9) Compare os erros (MAE e MSE) obtidos no conjunto de treinamento com os erros do conjunto de teste. Com base nessa comparação e no conceito de viés/variância, o modelo parece estar sofrendo de subajuste (underfitting), sobreajuste (overfitting) ou apresenta um bom ajuste? Justifique.</font>

Os erros de MAE são semelhantes, já os erros de MSE possuem uma diferença de 4. O modelo está sofrendo de subajuste (underfitting), pois os erros MAE e MSE de teste são menores que os erros de treino.

### <font color='cyan'>Q10) Treine um modelo de Regressão Polinomial (grau 2) para prever o MPG usando o peso. em seguida, Assim como na questão anterior, faça previsões e imprima as métricas (R², MAE e MSE) para os conjuntos de treinamento e de teste.</font>
- #### <font color='cyan'>Dica: Como as características polinomiais elevam os valores ao quadrado, a escala dos dados muda drasticamente. Utilize a classe `Pipeline` do Scikit-Learn para encadear a criação de `PolynomialFeatures(degree=2)`, a normalização com StandardScaler e o modelo LinearRegression.<font>
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

modelo_poly = Pipeline([
    ("poly", PolynomialFeatures(degree=2)),
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

modelo_poly.fit(X_train, y_train)

y_train_previsao_poly = modelo_poly.predict(X_train)
y_test_previsao_poly = modelo_poly.predict(X_test)

# Treino
r2_treino = r2_score(y_train, y_train_previsao_poly)
mae_treino = mean_absolute_error(y_train, y_train_previsao_poly)
mse_treino = mean_squared_error(y_train, y_train_previsao_poly)

# Teste
r2_teste = r2_score(y_test, y_test_previsao_poly)
mae_teste = mean_absolute_error(y_test, y_test_previsao_poly)
mse_teste = mean_squared_error(y_test, y_test_previsao_poly)

print("Treino:\n")
print("R2:", r2_treino)
print("MAE:", mae_treino)
print("MSE:", mse_treino)

print("\nTeste: \n")
print("R2:", r2_teste)
print("MAE:", mae_teste)
print("MSE:", mse_teste)

"""### <font color='cyan'>Q11) Avaliando os erros de treinamento e teste deste modelo polinomial (grau 2), como ele se compara ao modelo linear da questão anterior? Ele apresenta sinais de underfitting, overfitting ou um bom ajuste aos dados? Justifique.</font>

Os valores de R2 de ambos os modelos continuam com valores semelhantes, mas com os valores de MAE e MSE, o teste continua com valores menores que os valores de treino, mas com uma precisão mais alta do que a anterior, mostrando um bom ajuste.

### <font color='cyan'>Q12) Utilizando os modelos já treinados, construa um gráfico de dispersão com os dados reais de treinamento e teste (`weight` vs `mpg`), diferenciando-os por cores, e sobreponha, no mesmo gráfico, as curvas de predição dos modelos de Regressão Linear Simples e Regressão Polinomial (grau 2), incluindo título, rótulos dos eixos e legenda para identificar os subconjuntos e cada regressão.</font>
"""

import numpy as np

X_range = np.linspace(X["weight"].min(), X["weight"].max(), 100).reshape(-1, 1)

y_linear = modelo.predict(X_range)
y_poly = modelo_poly.predict(X_range)

plt.figure()

plt.scatter(X_train["weight"], y_train, label="Treino", alpha=0.7)
plt.scatter(X_test["weight"], y_test, label="Teste", alpha=0.7)

plt.plot(X_range, y_linear, label="Regressão Linear", color = 'purple')
plt.plot(X_range, y_poly, label="Regressão Polinomial (grau 2)", color = 'red')

plt.title("Relação peso vs MPG com Regressões (Linear e Polinomial)")
plt.xlabel("Peso")
plt.ylabel("MPG")
plt.legend()
plt.show()

"""### <font color='cyan'>Q13) Com base no gráfico gerado, qual modelo parece se ajustar melhor aos dados? A relação entre `weight` e `mpg` parece ser linear ou não linear? Explique.</font>

A relação é entre MPG e peso é linear de forma negativa, quanto maior o peso maior o consumo. O modelo que aparenta se ajustar melhor aos dados é o de Regressão Polinomial (Grau 2). pois a curva acompanha melhor os dados do que a reta.

### <font color='cyan'>Q14) Os resultados observados no gráfico são consistentes com a análise das métricas? Explique possíveis diferenças entre a avaliação quantitativa (métricas) e a avaliação visual do ajuste dos modelos.</font>

Sim, são consistentes. Nas avaliações visuais dos modelos, o modelo Polinomial se mostra melhor, devido aos valores de R2 serem semelhantes, MAE e MSE serem menores, além do modelo conseguir reproduzir a curvatura na relação de peso e MPG.

### <font color='cyan'>Q15) Para observar o efeito do sobreajuste (overfitting) na prática, treine um novo modelo de Regressão Polinomial, mas desta vez utilizando um grau bem alto (por exemplo, grau 15 ou 20). Utilize o mesmo processo com o Pipeline (incluindo o escalonamento). Imprima as métricas de treinamento e teste. O que acontece com o desempenho no conjunto de teste em comparação ao de treinamento? Explique o fenômeno ocorrido.</font>
"""

modelo_polinomial = Pipeline([
    ("poly", PolynomialFeatures(degree=20)),
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

modelo_polinomial.fit(X_train, y_train)

y_train_previsao_polinomial = modelo_polinomial.predict(X_train)
y_test_previsao_polinomial = modelo_polinomial.predict(X_test)

# Treino
r2_treino_2 = r2_score(y_train, y_train_previsao_polinomial)
mae_treino_2 = mean_absolute_error(y_train, y_train_previsao_polinomial)
mse_treino_2 = mean_squared_error(y_train, y_train_previsao_polinomial)

# Teste
r2_teste_2 = r2_score(y_test, y_test_previsao_polinomial)
mae_teste_2 = mean_absolute_error(y_test, y_test_previsao_polinomial)
mse_teste_2 = mean_squared_error(y_test, y_test_previsao_polinomial)

print("Treino:\n")
print("R2:", r2_treino_2)
print("MAE:", mae_treino_2)
print("MSE:", mse_treino_2)

print("\nTeste: \n")
print("R2:", r2_teste_2)
print("MAE:", mae_teste_2)
print("MSE:", mse_teste_2)

"""Os valores MAE e MSE do treino se mostraram melhores que os de teste, mostrando um leve overfitting mas quase um bom ajuste, o que acontece é a mudança da complexidade (grau = 20) e tendeu a se ajustar excessivamente aos dados de treino.

## <font color='green'>**3. Otimização com Gradiente Descendente**</font>

### <font color='cyan'>Q16) Tente treinar um `SGDRegressor` diretamente nos dados originais de `X` (removendo valores nulos se houver) e observe o erro.</font>
"""

from sklearn.linear_model import SGDRegressor

X = X.dropna() # Removendo os NaN
y = y.loc[X.index].squeeze()

modelo_sgd = Pipeline([
    ("sgd", SGDRegressor(random_state = 2))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state = 2
)

modelo_sgd.fit(X_train, y_train)

y_train_sgd= modelo_sgd.predict(X_train)
y_test_sgd = modelo_sgd.predict(X_test)

# Treino
r2_treino_sgd = r2_score(y_train, y_train_sgd)
mae_treino_sgd = mean_absolute_error(y_train, y_train_sgd)
mse_treino_sgd = mean_squared_error(y_train, y_train_sgd)

# Teste
r2_teste_sgd = r2_score(y_test, y_test_sgd)
mae_teste_sgd = mean_absolute_error(y_test, y_test_sgd)
mse_teste_sgd = mean_squared_error(y_test, y_test_sgd)

print("Treino:\n")
print("R2:", r2_treino_sgd)
print("MAE:", mae_treino_sgd)
print("MSE:", mse_treino_sgd)

print("\nTeste: \n")
print("R2:", r2_teste_sgd)
print("MAE:", mae_teste_sgd)
print("MSE:", mse_teste_sgd)

"""### <font color='cyan'>Q17) Agora, aplique o `StandardScaler` do Scikit-Learn nos dados e treine o `SGDRegressor` novamente.</font>"""

modelo_sgd = Pipeline([
    ("scaler", StandardScaler()),
    ("sgd", SGDRegressor(random_state = 2))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state = 2
)

modelo_sgd.fit(X_train, y_train)

y_train_sgd= modelo_sgd.predict(X_train)
y_test_sgd = modelo_sgd.predict(X_test)

# Treino
r2_treino_sgd = r2_score(y_train, y_train_sgd)
mae_treino_sgd = mean_absolute_error(y_train, y_train_sgd)
mse_treino_sgd = mean_squared_error(y_train, y_train_sgd)

# Teste
r2_teste_sgd = r2_score(y_test, y_test_sgd)
mae_teste_sgd = mean_absolute_error(y_test, y_test_sgd)
mse_teste_sgd = mean_squared_error(y_test, y_test_sgd)

print("Treino:\n")
print("R2:", r2_treino_sgd)
print("MAE:", mae_treino_sgd)
print("MSE:", mse_treino_sgd)

print("\nTeste: \n")
print("R2:", r2_teste_sgd)
print("MAE:", mae_teste_sgd)
print("MSE:", mse_teste_sgd)

"""### <font color='cyan'>Q18) Compare os resultados das duas abordagens e explique por que a normalização é importante para algoritmos baseados em gradiente descendente. Relacione sua resposta com o comportamento do gradiente e a escala das variáveis.</font>

Os resultados mostraram que normalização tem que ser aplicada, pois o método SGD é muito sensível à escala das variáveis, e o StandardScaler faz com que as variáveis fiquem na mesma escala, fazendo com que o algoritmo converja de forma mais eficiênte.

## <font color='green'>**4. Validação Cruzada e Regularização (LASSO)**</font>

### <font color='green'>A Regressão LASSO (Least Absolute Shrinkage and Selection Operator) é uma evolução da Regressão Linear tradicional. Na regressão comum, o modelo foca apenas em reduzir o erro. O problema é que, ao tentar usar todas as variáveis disponíveis, ele pode acabar decorando ruídos e gerando overfitting. O LASSO resolve isso adicionando uma penalidade aos coeficientes (pesos) das variáveis.</font>
- #### <font color='green'>O grande diferencial da regularização do LASSO (chamada de L1) é que ela consegue forçar os coeficientes de variáveis inúteis ou redundantes a se tornarem exatamente zero. Ou seja, o próprio modelo decide quais dados ignorar, entregando uma equação final mais simples, limpa e interpretável.</font>
- #### <font color='green'>O hiperparâmetro `alpha` é o "botão de volume" da penalidade. Se alpha = 0, temos uma regressão linear normal. Quanto maior o valor de alpha, mais severa é a penalização e mais atributos o modelo irá descartar.</font>

### <font color='green'>Caso queira entender a matemática por trás da função de custo, consulte os seguintes materiais:</font>
- #### <font color='green'>Anexo III do [material  teórico](https://github.com/zz4fap/c24_inteligencia_artificial/blob/main/slides/C24_Regress%C3%A3o.pdf) da disciplina  (slides 96 em diante);</font>
- #### <font color='green'>Documentação oficial do Scikit-Learn sobre [modelos lineares com LASSO](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html);</font>
- #### <font color='green'>Vídeo ["Regularization Part 2: Lasso (L1) Regression"](https://www.youtube.com/watch?v=NGf0voTMlcs), do canal "StatQuest with Josh Starmer", com uma explicação didática e visual sobre como a matemática do LASSO zera os coeficientes.</font>

### <font color='cyan'>Q19) O algoritmo LASSO é extremamente sensível à escala dos dados, pois ele penaliza a magnitude bruta dos coeficientes. Crie um `Pipeline` que aplique o `StandardScaler` e, em seguida, o modelo `Lasso(alpha=1.0)`. Treine-o com todos os dados (`X` e `y`) e exiba os coeficientes finais. A aplicação da normalização mudou a relevância que o modelo deu às variáveis em comparação com a Q16 (onde não usamos normalização)? Explique.</font>
"""

from sklearn import linear_model

lasso = Pipeline([("scaler", StandardScaler()),("lasso", linear_model.Lasso(alpha=1.0))])

lasso.fit(X, y)

coef = lasso.named_steps["lasso"].coef_

for nome, c in zip(X.columns, coef):
    print(f"{nome}: {c}")

"""A normalização alterou a forma que o modelo atribuiu a relevância às variáveis, no caso as de menos relevância foram para zero, e sem a normalização, não tem escala entre as variáveis, e elas são punidas de forma menos justa, assim o StandardScaler aplicou uma escala para calcular corretamente.

### <font color='cyan'>Q20) O hiperparâmetro alpha é quem dita a força da regularização. Utilizando o mesmo processo com o Pipeline e o StandardScaler, treine três modelos LASSO distintos, alterando o valor de alpha para: 0.1, 1.0 e 5.0. Imprima apenas os nomes das variáveis que "sobreviveram" (ou seja, que tiveram coeficientes diferentes de zero) em cada modelo. O que acontece com a complexidade do modelo à medida que o valor de alpha aumenta?</font>
"""

lasso_01 = Pipeline([("scaler", StandardScaler()),("lasso", linear_model.Lasso(alpha=0.1))])

lasso_01.fit(X, y)

coef_01 = lasso_01.named_steps["lasso"].coef_

for nome, c in zip(X.columns, coef_01):
    if c != 0:
        print(nome, "=", c)

print("\n===========================================\n")

lasso_02 = Pipeline([("scaler", StandardScaler()),("lasso", linear_model.Lasso(alpha=1.0))])

lasso_02.fit(X, y)

coef_02 = lasso_02.named_steps["lasso"].coef_

for nome, c in zip(X.columns, coef_02):
    if c != 0:
        print(nome, "=", c)

print("\n===========================================\n")

lasso_03 = Pipeline([("scaler", StandardScaler()),("lasso", linear_model.Lasso(alpha=5.0))])

lasso_03.fit(X, y)

coef_03 = lasso_03.named_steps["lasso"].coef_

for nome, c in zip(X.columns, coef_03):
    if c != 0:
        print(nome, "=", c)

"""A complexidade diminui, fazendo com o que a penalidade sobre as varáveis aumente e mandem o valor para zero."""